export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
export const UPDATE_ITEM_IN_CART = "UPDATE_ITEM_IN_CART"
export const SET_PRODUCTS = "SET_PRODUCTS"
